all:
	g++ -o FIS_Server FIS_Server.cpp
	g++ -o Peer_Server Peer_Server.cpp
	g++ -o Peer_Client Peer_Client.cpp

1:
	rm -f FIS_Server
	g++ -o FIS_Server FIS_Server.cpp

2:
	rm -f Peer_Server
	g++ -o Peer_Server Peer_Server.cpp

3:
	rm -f Peer_Client
	g++ -o Peer_Client Peer_Client.cpp

clean:
	rm -f FIS_Server Peer_Client Peer_Server
